global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: ""
  ingress:
    domain: ''

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 60
resetOnConfigChange: true
imagePullPolicy: Always


nameOverride: ""
fullnameOverride: ""

cloudProvider:
  dockerRegistryUrl: my-registry-url
  imagePullSecretName: imagepullsecret
  flavor: openshift

caSecretName: ''
caPath: '/usr/local/share/ca-certificates'
caKey: 'ca.crt'

image:
  repository: nginx
  tag: 'latest' 
port: 8080
internalServicePort: 80
targetPort: 8080
siteStatusPort: 8081
nodePort: 30001
resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

additionalPodAnnotations: {}

# Add extra volumes to the Deployment, for example
# - name: nginx-config
#   configMap:
#    name: 'nginx-extra-configmap'
extraVolumes: []

# Add extra volumeMounts to the Pod, for example
# - name: nginx-config
#   mountPath: "/etc/nginx/conf.d/default.conf"
#   subPath: default.conf
extraVolumeMounts: []

# Add side car to the Deployment, for example
# sidecars: |-
#   - name: envoy
#     image: "{{ .Values.envoy.image }}:{{ .Values.envoy.imageTag }}"
#     volumeMounts: []
#     args: []
#     ports: []
#     resources:
#     {{- toYaml .Values.envoy.resources.value | nindent 12 }}
sidecars: ''

env:
  opentelemetry:
    serviceName: nginx
    exporterEndpoint: localhost:4317
    samplerMethod: "AlwaysOff" # AlwaysOn, AlwaysOff, TraceIdRatioBased
    ratio: 0.1 # between 0 and 1
    parentBased: "false" # true, false

prometheusExporter:
  enabled: false
  image:
    repository: nginx/nginx-prometheus-exporter
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    enabled: true
    value:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi  

authorization:
  enabled: true
  domain: 'example'
  url: 'http://localhost:8181/v1/data/http/authz/decision'

route:
  enabled: true
  path: /
  host: 
  timeout:
    enabled: false # defaults to 30s by openshift
    duration: 60s # supported units (us, ms, s, m, h, d)
  rewriteTarget: ''
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    useCerts: false
    certificate: ''
    key: ''
    caCertificate: ''

ingress:
  enabled: false
  path: /
  host: ''
  domain: ''
  tls: 
    enabled: true
    secretName: ''
